// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(FormContext))]
    partial class FormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Fantasy",
                            Director = "Dave Filoni",
                            Edited = false,
                            LentTo = "John",
                            Notes = "Uncle Iroh is the best",
                            Rating = "G",
                            Title = "Avatar the Last Airbender",
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Fantasy",
                            Director = "Alfonso Cuaron",
                            Edited = true,
                            LentTo = "Dustin",
                            Notes = "The best of all the Harry Potter Movies",
                            Rating = "PG",
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            Year = 2004
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "RomCom",
                            Director = "Michael Curtiz",
                            Edited = false,
                            LentTo = "Jackson",
                            Notes = "Best Christmas movie ever. (Should watch at least 5 times per year)",
                            Rating = "G",
                            Title = "White Christmas",
                            Year = 1954
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
